export const REGIONS = ["CLD-CTC", "CLD-EMEA", "CLD-HQ"]

export const REGION_BUILD_CAPACITY = {
  "CLD-CTC": 2,
  "CLD-EMEA": 4,
  "CLD-HQ": 3,
}

export const SEED_BOOKINGS = [
  {
    id: "pb-0001",
    status: "approved",
    region: "CLD-EMEA",
    operationType: "refresh",
    operationLabel: "MD Refresh",
    title: "MD Refresh PROD to PREF",
    cid: "C560",
    environment: "PROD",
    start: "2026-06-18",
    end: "2026-06-18",
    startTime: "8:30 AM",
    endTime: "4:30 PM",
    durationHours: 8,
    tier: "prod_large",
    bookerName: "J. Okafor",
    csmEmail: "jokafor@example.com",
  },
  {
    id: "pb-0002",
    status: "approved",
    region: "CLD-EMEA",
    operationType: "build",
    operationLabel: "Environment Build",
    title: "PROD parallel build",
    cid: "C689",
    environment: "PROD",
    start: "2026-06-22",
    end: "2026-06-26",
    durationHours: 40,
    bookerName: "M. Delgado",
    csmEmail: "mdelgado@example.com",
  },
  {
    id: "pb-0003",
    status: "pending",
    region: "CLD-EMEA",
    operationType: "refresh",
    operationLabel: "MD Refresh",
    title: "QA refresh",
    cid: "C560",
    environment: "QA",
    start: "2026-06-23",
    end: "2026-06-23",
    startTime: "10:00 AM",
    endTime: "4:00 PM",
    durationHours: 6,
    tier: "lower",
    bookerName: "T. Novak",
    csmEmail: "tnovak@example.com",
  },
  {
    id: "pb-0004",
    status: "approved",
    region: "CLD-HQ",
    operationType: "build",
    operationLabel: "Environment Build",
    title: "DEV parallel build",
    cid: "C802",
    environment: "DEV",
    start: "2026-06-15",
    end: "2026-06-19",
    durationHours: 40,
    bookerName: "S. Whitfield",
    csmEmail: "swhitfield@example.com",
  },
  {
    id: "pb-0005",
    status: "approved",
    region: "CLD-HQ",
    operationType: "cutover",
    operationLabel: "Cutover",
    title: "Cutover C802",
    cid: "C802",
    environment: "PROD",
    start: "2026-06-19",
    end: "2026-06-19",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
    durationHours: 2,
    bookerName: "L. Ferraro",
    csmEmail: "lferraro@example.com",
  },
  {
    id: "pb-0006",
    status: "pending",
    region: "CLD-HQ",
    operationType: "cutover",
    operationLabel: "Cutover",
    title: "Cutover C757",
    cid: "C757",
    environment: "DEV",
    start: "2026-06-22",
    end: "2026-06-22",
    startTime: "1:00 PM",
    endTime: "3:00 PM",
    durationHours: 2,
    bookerName: "R. Banerjee",
    csmEmail: "rbanerjee@example.com",
  },
  {
    id: "pb-0007",
    status: "approved",
    region: "CLD-CTC",
    operationType: "refresh",
    operationLabel: "MD Refresh",
    title: "UAT refresh",
    cid: "C689",
    environment: "UAT",
    start: "2026-06-24",
    end: "2026-06-24",
    startTime: "8:30 AM",
    endTime: "2:30 PM",
    durationHours: 6,
    tier: "lower",
    bookerName: "H. Park",
    csmEmail: "hpark@example.com",
  },
  {
    id: "pb-0008",
    status: "cancelled",
    region: "CLD-CTC",
    operationType: "cutover",
    operationLabel: "Cutover",
    title: "Cutover C560 (cancelled)",
    cid: "C560",
    environment: "PROD",
    start: "2026-06-16",
    end: "2026-06-16",
    startTime: "11:30 AM",
    endTime: "1:30 PM",
    durationHours: 2,
    bookerName: "E. Castellano",
    csmEmail: "ecastellano@example.com",
  },
  {
    id: "pb-0009",
    status: "approved",
    region: "CLD-CTC",
    operationType: "build",
    operationLabel: "Environment Build",
    title: "DR parallel build",
    cid: "C701",
    environment: "DR",
    start: "2026-06-22",
    end: "2026-06-26",
    durationHours: 40,
    bookerName: "N. Abadi",
    csmEmail: "nabadi@example.com",
  },
  {
    id: "pb-0010",
    status: "pending",
    region: "CLD-CTC",
    operationType: "build",
    operationLabel: "Environment Build",
    title: "SBX parallel build",
    cid: "C702",
    environment: "SBX",
    start: "2026-06-23",
    end: "2026-06-29",
    durationHours: 40,
    bookerName: "G. Vasquez",
    csmEmail: "gvasquez@example.com",
  },
]

// Map a booking-form payload into a calendar record. This is the seam between
// the two surfaces — when create writes to the shared store, it runs through here.
export function fromFormPayload(p, id) {
  const isBuild = p.operationType === "build"
  return {
    id,
    status: "pending",
    region: null, // assignment / region is decided later (manager step, TBD)
    operationType: p.operationType,
    operationLabel: p.operationLabel,
    title: p.operationLabel,
    cid: p.cid,
    environment: p.environment,
    environmentId: p.environmentId,
    start: isBuild ? p.buildWindowStart : p.date,
    end: isBuild ? p.buildWindowEnd : p.date,
    startTime: p.startTime,
    endTime: p.endTime,
    durationHours: p.durationHours,
    tier: p.tier,
    bookerName: p.bookerName,
    csmEmail: p.csmEmail,
    utilityBox: p.utilityBox,
    privateNotes: p.privateNotes,
  }
}

export const REGION_TZ = {
  "CLD-CTC":  "Asia/Shanghai",
  "CLD-EMEA": "Europe/London",
  "CLD-HQ":   "America/New_York",
}

// Region-local wall-clock slots — vary the count per region freely.
export const REGION_SLOTS = {
  "CLD-CTC":  ["9:00 AM", "10:30 AM", "1:00 PM"],                       // 3/day
  "CLD-EMEA": ["8:30 AM", "10:00 AM", "11:30 AM", "1:00 PM", "2:30 PM"],// 5/day
  "CLD-HQ":   ["8:30 AM", "10:00 AM", "11:30 AM", "1:00 PM"],           // 4/day
}